<?php
	return array(
		'wd/accordion'                    => array(),
		'wd/accordion-pane'               => array(),
		'wd/row'                          => array(),
		'wd/column'                       => array(),
		'wd/section'                      => array(),
		'wd/paragraph'                    => array(),
		'wd/title'                        => array(),
		'wd/button'                       => array(),
		'wd/icon'                         => array(),
		'wd/image'                        => array(),
		'wd/cover'                        => array(
			'attributes' => wd_get_block_cover_attrs(),
		),
		'wd/divider'                      => array(),
		'wd/gallery'                      => array(),
		'wd/gallery-item'                 => array(),
		'wd/infobox'                      => array(),
		'wd/off-canvas'                   => array(),
		'wd/off-sidebar'                  => array(),
		'wd/off-content'                  => array(),
		'wd/off-canvas-button'            => array(),
		'wd/tabs'                         => array(),
		'wd/toggle'                       => array(),
		'wd/toggle-content'               => array(),
		'wd/tabs-header'                  => array(),
		'wd/tabs-content'                 => array(),
		'wd/tabs-content-tab'             => array(),
		'wd/hotspots'                     => array(),
		'wd/hotspot'                      => array(),
		'wd/timeline'                     => array(),
		'wd/timeline-item'                => array(),
		'wd/timeline-breakpoint'          => array(),
		'wd/menu-price'                   => array(),
		'wd/table'                        => array(),
		'wd/collapsible-content'          => array(),
		'wd/quote'                        => array(),
		'wd/marquee'                      => array(
			'render_callback' => 'wd_gutenberg_marquee',
		),
		'wd/marquee-item'                 => array(),
		'wd/hotspot-product'              => array(
			'render_callback' => 'wd_gutenberg_hotspot_product_block',
			'attributes'      => wd_get_block_hotspot_product_attrs(),
		),
		'wd/container'                    => array(
			'attributes' => wd_get_block_container_attrs(),
		),
		'wd/carousel'                     => array(),
		'wd/carousel-item'                => array(),
		'wd/popup'                        => array(),
		'wd/popup-content'                => array(),
		'wd/products'                     => array(
			'attributes'      => wd_get_block_products_attrs(),
			'render_callback' => 'wd_gutenberg_products',
		),
		'wd/product-categories'           => array(
			'attributes'      => wd_get_block_product_categories_attrs(),
			'render_callback' => 'wd_gutenberg_product_categories',
		),
		'wd/blog'                         => array(
			'attributes'      => wd_get_block_blog_attrs(),
			'render_callback' => 'wd_gutenberg_blog',
		),
		'wd/breadcrumbs'                  => array(
			'attributes'      => wd_get_block_breadcrumbs_attrs(),
			'render_callback' => 'wd_gutenberg_breadcrumbs',
		),
		'wd/portfolio'                    => array(
			'attributes'      => wd_get_block_portfolio_attrs(),
			'render_callback' => 'wd_gutenberg_portfolio',
		),
		'wd/product-filters'              => array(
			'attributes'      => wd_get_block_product_filters_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters',
			'subfolder'       => 'product-filters',
		),
		'wd/product-filters-categories'   => array(
			'attributes'      => wd_get_block_product_filters_categories_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters_categories',
			'subfolder'       => 'product-filters',
		),
		'wd/product-filters-attributes'   => array(
			'attributes'      => wd_get_block_product_filters_attributes_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters_attributes',
			'subfolder'       => 'product-filters',
		),
		'wd/product-filters-stock-status' => array(
			'attributes'      => wd_get_block_product_filters_stock_status_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters_stock_status',
			'subfolder'       => 'product-filters',
		),
		'wd/product-filters-prices'       => array(
			'attributes'      => wd_get_block_product_filters_price_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters_price',
			'subfolder'       => 'product-filters',
		),
		'wd/product-filters-orderby'      => array(
			'attributes'      => wd_get_block_product_filters_orderby_attrs(),
			'render_callback' => 'wd_gutenberg_product_filters_orderby',
			'subfolder'       => 'product-filters',
		),
		'wd/brands'                       => array(
			'attributes'      => wd_get_block_brands_attrs(),
			'render_callback' => 'wd_gutenberg_brands',
		),
		'wd/products-tabs'                => array(
			'subfolder' => 'products-tabs',
		),
		'wd/products-tabs-header'         => array(
			'subfolder' => 'products-tabs',
		),
		'wd/products-tabs-products'       => array(
			'attributes'      => wd_get_block_products_attrs(),
			'render_callback' => 'wd_gutenberg_products_tab',
			'subfolder'       => 'products-tabs',
		),
		'wd/products-tabs-tab'            => array(
			'attributes' => wd_get_block_products_attrs(),
			'subfolder'  => 'products-tabs',
		),
		'wd/social-buttons'               => array(
			'attributes'      => wd_get_block_social_buttons_attrs(),
			'render_callback' => 'wd_gutenberg_social_buttons',
		),
		'wd/menu'                         => array(
			'attributes'      => wd_get_block_menu_attrs(),
			'render_callback' => 'wd_gutenberg_menu',
		),
		'wd/ajax-search'                  => array(
			'attributes'      => wd_get_block_ajax_search_attrs(),
			'render_callback' => 'wd_gutenberg_ajax_search',
		),
		'wd/instagram'                    => array(
			'attributes'      => wd_get_block_instagram_attrs(),
			'render_callback' => 'wd_gutenberg_instagram',
		),
		'wd/sidebar'                      => array(
			'attributes'      => wd_get_block_sidebar_attrs(),
			'render_callback' => 'wd_gutenberg_sidebar',
		),
		'wd/contact-form-7'               => array(
			'attributes'      => wd_get_block_contact_form_attrs(),
			'render_callback' => 'wd_gutenberg_contact_form',
		),
		'wd/mailchimp'                    => array(
			'attributes'      => wd_get_block_mailchimp_attrs(),
			'render_callback' => 'wd_gutenberg_mailchimp',
		),
		'wd/video'                        => array(
			'attributes' => wd_get_block_video_attrs(),
		),
		'wd/animated-counter'             => array(),
		'wd/countdown-timer'              => array(),
		'wd/slider'                       => array(
			'attributes' => wd_get_block_slider_attrs(),
		),
		'wd/slider-item'                  => array(),
		'wd/menu-list'                    => array(),
		'wd/menu-list-item'               => array(),
		'wd/list'                         => array(),
		'wd/list-item'                    => array(),
		'wd/testimonial'                  => array(),
		'wd/star-rating'                  => array(),
		'wd/team-member'                  => array(),
		'wd/google-map'                   => array(
			'attributes' => wd_get_block_google_map_attrs(),
		),
		'wd/open-street-map'              => array(
			'attributes' => wd_get_block_open_street_map_attrs(),
		),
		'wd/page-heading'                 => array(
			'attributes'      => wd_get_page_heading_block_title_attrs(),
			'render_callback' => 'wd_gutenberg_page_heading',
		),
		'wd/degree-view'                  => array(),
		'wd/menu-anchor'                  => array(),
		'wd/design-library'               => array(),
		'wd/compare-images'               => array(),
		'wd/size-guide'                   => array(
			'attributes'      => wd_get_block_size_guide_attrs(),
			'render_callback' => 'wd_gutenberg_size_guide',
		),
	);
